services:

  rabbitmq:
    image: rabbitmq:4-management
    container_name: investment-qe-rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: iqe_user
      RABBITMQ_DEFAULT_PASS: iqe_password

    ports:
      - "5672:5672"
      - "15672:15672"

    healthcheck:
      test:
        [
          "CMD",
          "rabbitmq-diagnostics",
          "-q",
          "ping"
        ]
      interval: 5s
      timeout: 5s
      retries: 12

    restart: unless-stopped